## 1. Data Cleaning & Pre-processing
In this section, we prepare the raw bank marketing data for analysis. This includes handling missing values, duplicates, and converting categorical strings into numeric formats for statistical modeling.

In [145]:
# Importing necessary libraries
import pandas as pd
import numpy as np

In [146]:
# Reading .csv file and verifying data

df=pd.read_csv('../raw_data/bank.csv')
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes

### 1.1 Integrity Check
We check for duplicate, null rows to ensure that our conversion rates aren't skewed by repeated, empty entries.

In [147]:
# Counting how many null rows we have in dataset

df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [148]:
# Checking the size of dataset

df.shape

(11162, 17)

In [149]:
# Checking the types of columns

df.dtypes

age          int64
job            str
marital        str
education      str
default        str
balance      int64
housing        str
loan           str
contact        str
day          int64
month          str
duration     int64
campaign     int64
pdays        int64
previous     int64
poutcome       str
deposit        str
dtype: object

In [150]:
# Counting if we have duplicates

print(df.duplicated().sum())

0

### 1.2 Binary Encoding
Several columns contain 'yes' or 'no' strings (e.g., deposit, housing, loan). We convert these into binary integers (1 and 0) so we can calculate means, correlations, and success rates.

In [151]:
cols_to_fix=['default', 'deposit', 'loan', 'housing']
for col in cols_to_fix:
    df[f'{col}_num']=df[col].map({'yes':1, 'no':0})

df=df.drop(columns=cols_to_fix)
df.head()

,age,job,marital,education,balance,contact,day,month,duration,campaign,pdays,previous,poutcome,default_num,deposit_num,loan_num,housing_num
0,59,admin.,married,secondary,2343,unknown,5,may,1042,1,-1,0,unknown,0,1,0,1
1,56,admin.,married,secondary,45,unknown,5,may,1467,1,-1,0,unknown,0,1,0,0
2,41,technician,married,secondary,1270,unknown,5,may,1389,1,-1,0,unknown,0,1,0,1
3,55,services,married,secondary,2476,unknown,5,may,579,1,-1,0,unknown,0,1,0,1
4,54,admin.,married,tertiary,184,unknown,5,may,673,2,-1,0,unknown,0,1,0,0

### 1.3 Handling Temporal Data
The 'month' column is currently a string. We convert it to an ordered Categorical type to ensure that visualizations follow the chronological order of the calendar year rather than alphabetical order.

In [152]:
month_order=['jan', 'feb', 'mar','apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']
df['month']=pd.Categorical(df['month'], categories=month_order, ordered=True)
df.head()

,age,job,marital,education,balance,contact,day,month,duration,campaign,pdays,previous,poutcome,default_num,deposit_num,loan_num,housing_num
0,59,admin.,married,secondary,2343,unknown,5,may,1042,1,-1,0,unknown,0,1,0,1
1,56,admin.,married,secondary,45,unknown,5,may,1467,1,-1,0,unknown,0,1,0,0
2,41,technician,married,secondary,1270,unknown,5,may,1389,1,-1,0,unknown,0,1,0,1
3,55,services,married,secondary,2476,unknown,5,may,579,1,-1,0,unknown,0,1,0,1
4,54,admin.,married,tertiary,184,unknown,5,may,673,2,-1,0,unknown,0,1,0,0

### 1.4 Duration to minutes
The raw 'duration' of the calls was recorded in seconds. We transformed this into a new feature, duration_min, to make the data more interpretable for business reporting. The original 'duration' column was then dropped to maintain a lean dataset.

In [153]:
df['duration_min']=df['duration']/60
df=df.drop(columns=['duration'])
df.head()

,age,job,marital,education,balance,contact,day,month,campaign,pdays,previous,poutcome,default_num,deposit_num,loan_num,housing_num,duration_min
0,59,admin.,married,secondary,2343,unknown,5,may,1,-1,0,unknown,0,1,0,1,17.366667
1,56,admin.,married,secondary,45,unknown,5,may,1,-1,0,unknown,0,1,0,0,24.450000
2,41,technician,married,secondary,1270,unknown,5,may,1,-1,0,unknown,0,1,0,1,23.150000
3,55,services,married,secondary,2476,unknown,5,may,1,-1,0,unknown,0,1,0,1,9.650000
4,54,admin.,married,tertiary,184,unknown,5,may,2,-1,0,unknown,0,1,0,0,11.216667

In [154]:
df.head()

,age,job,marital,education,balance,contact,day,month,campaign,pdays,previous,poutcome,default_num,deposit_num,loan_num,housing_num,duration_min
0,59,admin.,married,secondary,2343,unknown,5,may,1,-1,0,unknown,0,1,0,1,17.366667
1,56,admin.,married,secondary,45,unknown,5,may,1,-1,0,unknown,0,1,0,0,24.450000
2,41,technician,married,secondary,1270,unknown,5,may,1,-1,0,unknown,0,1,0,1,23.150000
3,55,services,married,secondary,2476,unknown,5,may,1,-1,0,unknown,0,1,0,1,9.650000
4,54,admin.,married,tertiary,184,unknown,5,may,2,-1,0,unknown,0,1,0,0,11.216667

In [155]:
df.to_csv('processed_data/bank_cleaned.csv', index=False)

OSError: Cannot save file into a non-existent directory: 'processed_data'